import { DataTypes } from 'sequelize';

export default (sequelize) => {
  return sequelize.define('SecurityFinding', {
    id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
    sourceTool: { type: DataTypes.STRING(64), allowNull: false },
    externalEventId: { type: DataTypes.STRING(255), allowNull: true },
    fingerprint: { type: DataTypes.STRING(128), allowNull: true, unique: true },
    detectionMode: { type: DataTypes.ENUM('passive', 'active'), allowNull: false },
    category: { type: DataTypes.STRING(64), allowNull: false },
    severity: { type: DataTypes.ENUM('low', 'medium', 'high', 'critical'), allowNull: false },
    confidenceScore: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 70 },
    likelihoodScore: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 65 },
    impactScore: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 70 },
    riskScore: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 60 },
    riskBand: { type: DataTypes.ENUM('low', 'medium', 'high', 'critical'), allowNull: false, defaultValue: 'medium' },
    cveId: { type: DataTypes.STRING(32), allowNull: true },
    cweId: { type: DataTypes.STRING(32), allowNull: true },
    mitreTechnique: { type: DataTypes.STRING(32), allowNull: true },
    affectedAssetType: { type: DataTypes.STRING(64), allowNull: true },
    affectedAssetRef: { type: DataTypes.STRING(255), allowNull: true },
    detectedAt: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
    title: { type: DataTypes.STRING(255), allowNull: false },
    description: { type: DataTypes.TEXT, allowNull: false },
    executiveSummary: { type: DataTypes.TEXT, allowNull: true },
    businessImpact: { type: DataTypes.TEXT, allowNull: true },
    remediationRecommendation: { type: DataTypes.TEXT, allowNull: true },
    evidence: { type: DataTypes.TEXT, allowNull: true },
    rawPayload: { type: DataTypes.TEXT, allowNull: true },
    status: { type: DataTypes.ENUM('new', 'investigating', 'remediated', 'dismissed'), allowNull: false, defaultValue: 'new' },
    requiresManualConfirmation: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    manualConfirmed: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    manualConfirmedBy: { type: DataTypes.STRING(128), allowNull: true },
    autoTicketCreated: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    ticketId: { type: DataTypes.INTEGER, allowNull: true },
    firstSeenAt: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
    lastSeenAt: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
  });
};
